export enum MudStatusCode {
    OK = 200,
    CREATED = 201,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    INTERNAL_SERVER_ERROR = 500
}

const RANK_KEY = "RANK";
const RANK_NONE = "NONE";
const RANK_BRONZE = "BRONZE";
const RANK_SILVER = "SILVER";
const RANK_GOLD = "GOLD";
const RANK_PLAT = "PLATINUM";
const RANK_DIAMOND = "DIMAOND";

export {
    RANK_KEY,
    RANK_NONE,
    RANK_BRONZE,
    RANK_SILVER,
    RANK_GOLD,
    RANK_PLAT,
    RANK_DIAMOND
}
